### ISSUE TITLE
Cannot find module 'pg-escape'

### ISSUE THREAD

**Issue by strarsis** [Vincit/knex-db-manager#8]
Package 'pg-escape' is missing in package.json of this module:
```js
Error: Cannot find module 'pg-escape'
````

**Comment by elhigu** [comment]
Thanks for the report. Actually all driver related modules are missing from package.json, since package was planned to work with multiple different databases without need to install all the drivers. 

However at least better error message would be good to have to tell the user list of required additional packages.

**Comment by elhigu** [comment]
Added this one to documentation page npm install command.
